#!/bin/sh
# Provides: smartcard-init
# Starts IFD-NFC on boot.

start() {
    if command -v ifdnfc-activate >/dev/null 2>&1; then
        echo "Activating IFD-NFC"
        ifdnfc-activate yes
    fi
}

stop() {
    if command -v ifdnfc-activate >/dev/null 2>&1; then
        ifdnfc-activate no
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 5
        ;;
esac

exit $?
