#!/bin/sh
# Provides: pcscd

start() {
    pcscd &
    echo "PCSC Service starting up"   
}

stop () {    
    killall pcscd &
    echo "PCSC Service shutting down"
}

restart () {    
    killall pcscd &
    echo "PCSC Service shutting down" &
    sleep 1 &
    pcscd &
    echo "PCSC Service starting up"
}

reload () {
	pcscd --hotplug
    echo "Reloading PCSC Service"
}

##case statement to be used to call functions##
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart 
        ;;
    reload)
        reload 
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 5
esac
exit $?
