################################################################################
#
# python-cryptography
#
################################################################################

PYTHON_CRYPTOGRAPHY_VERSION = 43.0.3
PYTHON_CRYPTOGRAPHY_SOURCE_PYPI = cryptography-$(PYTHON_CRYPTOGRAPHY_VERSION).tar.gz
PYTHON_CRYPTOGRAPHY_SITE_PYPI = https://files.pythonhosted.org/packages/0d/05/07b55d1fa21ac18c3a8c79f764e2514e6f6a9698f1be44994f5adf0d29db
PYTHON_CRYPTOGRAPHY_SITE = $(PYTHON_CRYPTOGRAPHY_SITE_PYPI)/$(PYTHON_CRYPTOGRAPHY_SOURCE_PYPI)?buildroot-path=filename
PYTHON_CRYPTOGRAPHY_SETUP_TYPE = maturin
PYTHON_CRYPTOGRAPHY_LICENSE = Apache-2.0 or BSD-3-Clause
PYTHON_CRYPTOGRAPHY_LICENSE_FILES = LICENSE LICENSE.APACHE LICENSE.BSD
PYTHON_CRYPTOGRAPHY_CPE_ID_VENDOR = cryptography_project
PYTHON_CRYPTOGRAPHY_CPE_ID_PRODUCT = cryptography
PYTHON_CRYPTOGRAPHY_CARGO_MANIFEST_PATH = src/rust/Cargo.toml
PYTHON_CRYPTOGRAPHY_DEPENDENCIES = \
	host-python-cffi \
	host-python-setuptools \
	openssl
HOST_PYTHON_CRYPTOGRAPHY_DEPENDENCIES = \
	host-python-cffi \
	host-python-setuptools \
	host-openssl
PYTHON_CRYPTOGRAPHY_BUILD_OPTS = --skip-dependency-check
HOST_PYTHON_CRYPTOGRAPHY_BUILD_OPTS = --skip-dependency-check

PYTHON_CRYPTOGRAPHY_ASCII_BUILDDIR = /tmp/python-cryptography-build
PYTHON_CRYPTOGRAPHY_ASCII_PYTHON3_DIR = /tmp/python-cryptography-python3-build

define PYTHON_CRYPTOGRAPHY_BUILD_CMDS
	ln -sfn $(PYTHON_CRYPTOGRAPHY_BUILDDIR) $(PYTHON_CRYPTOGRAPHY_ASCII_BUILDDIR)
	ln -sfn $(PYTHON3_DIR) $(PYTHON_CRYPTOGRAPHY_ASCII_PYTHON3_DIR)
	(cd $(PYTHON_CRYPTOGRAPHY_ASCII_BUILDDIR)/; \
		$(PKG_PYTHON_MATURIN_ENV) \
		_PYTHON_PROJECT_BASE="$(PYTHON_CRYPTOGRAPHY_ASCII_PYTHON3_DIR)" \
		PYO3_CROSS_LIB_DIR="$(if $(BR2_MESON_STAGING_DIR),$(BR2_MESON_STAGING_DIR),$(STAGING_DIR))/usr/lib/python$(PYTHON3_VERSION_MAJOR)" \
		$(PYTHON_CRYPTOGRAPHY_ENV) \
		"$(if $(BR2_MESON_HOST_DIR),$(BR2_MESON_HOST_DIR),$(HOST_DIR))/bin/python3" \
		$(PKG_PYTHON_MATURIN_BUILD_CMD) \
		$(PYTHON_CRYPTOGRAPHY_BUILD_OPTS))
endef

$(eval $(python-package))
$(eval $(host-python-package))
